version: "3.8"

services:
  ts-converter:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - "./static:/app/static"
